#ifndef CRYPTO_SIMPLE_TABLE_H
#define CRYPTO_SIMPLE_TABLE_H

#define CRYPTO_SIMPLE_TABLE_ERROR crypto_simple_table_error_quark()

typedef enum {
    CRYPTO_SIMPLE_TABLE_ERROR_FAILED,
    CRYPTO_SIMPLE_TABLE_ERROR_TEXT_NOT_UTF8,
    CRYPTO_SIMPLE_TABLE_ERROR_TEXT_NOT_IN_ALPHABET,
    CRYPTO_SIMPLE_TABLE_ERROR_INVALID_KEY
} crypto_simple_table_error;

#endif // CRYPTO_SIMPLE_TABLE_H
