#ifndef CAESAR_H
#define CAESAR_H

#include <glib.h>

#define CRYPTO_CAESAR_MODULE_FILENAME "crypto_caesar"

#define CRYPTO_CAESAR_ERROR crypto_caesar_error_quark()

typedef enum {
    CRYPTO_CAESAR_ERROR_FAILED,
    CRYPTO_CAESAR_ERROR_TEXT_NOT_UTF8,
    CRYPTO_CAESAR_ERROR_TEXT_NOT_IN_ALPHABET,
    CRYPTO_CAESAR_ERROR_KEYWORD_TOO_LONG,
    CRYPTO_CAESAR_ERROR_KEYWORD_NOT_UNIQUE,
    CRYPTO_CAESAR_ERROR_CAESAR_INVALID_OFFSET,
    CRYPTO_CAESAR_ERROR_INVALID_KEY
} crypto_caesar_error;

#endif // CAESAR_H
