#ifndef CRYPTO_VIGENERE_H
#define CRYPTO_VIGENERE_H

#define CRYPTO_VIGENERE_ERROR crypto_vigenere_error_quark()

typedef enum {
    CRYPTO_VIGENERE_ERROR_FAILED,
    CRYPTO_VIGENERE_ERROR_TEXT_NOT_UTF8,
    CRYPTO_VIGENERE_ERROR_TEXT_NOT_IN_ALPHABET,
    CRYPTO_VIGENERE_ERROR_KEYWORD_TOO_LONG,
    CRYPTO_VIGENERE_ERROR_KEYWORD_NOT_UNIQUE,
    CRYPTO_VIGENERE_ERROR_INVALID_KEY
} crypto_vigenere_error;

#endif // CRYPTO_VIGENERE_H
