#ifndef CRYPTO_CAESAR_ATHENS_H
#define CRYPTO_CAESAR_ATHENS_H

#define CRYPTO_CAESAR_ATHENS_ERROR crypto_caesar_athens_error_quark()

typedef enum {
    CRYPTO_CAESAR_ATHENS_ERROR_FAILED,
    CRYPTO_CAESAR_ATHENS_ERROR_TEXT_NOT_UTF8,
    CRYPTO_CAESAR_ATHENS_ERROR_TEXT_NOT_IN_ALPHABET,
    CRYPTO_CAESAR_ATHENS_ERROR_INVALID_OFFSET,
    CRYPTO_CAESAR_ATHENS_ERROR_INVALID_MULTIPLIER,
    CRYPTO_CAESAR_ATHENS_ERROR_INVALID_GCD,
    CRYPTO_CAESAR_ATHENS_ERROR_INVALID_KEY
} crypto_caesar_athens_error;

#endif // CRYPTO_CAESAR_ATHENS_H
