#ifndef CRYPTO_GAMMA_H
#define CRYPTO_GAMMA_H

#define CRYPTO_GAMMA_ERROR crypto_gamma_error_quark()

typedef enum {
    CRYPTO_GAMMA_ERROR_FAILED,
    CRYPTO_GAMMA_ERROR_TEXT_NOT_UTF8,
    CRYPTO_GAMMA_ERROR_TEXT_NOT_IN_ALPHABET,
    CRYPTO_GAMMA_ERROR_KEYWORD_TOO_LONG,
    CRYPTO_GAMMA_ERROR_KEYWORD_NOT_UNIQUE,
    CRYPTO_GAMMA_ERROR_INVALID_OFFSET,
    CRYPTO_GAMMA_ERROR_INVALID_KEY
} crypto_gamma_error;

#endif // CRYPTO_GAMMA_H
